### ISSUE TITLE
Support flake8 v5+

### ISSUE THREAD

**Issue by PeterJCLaw** [atollk/flake8-typing-collections#1]
In flake8 v5 plugin error codes became limited to a stricter patten: `^[A-Z]{1,3}[0-9]{0,3}$`, which unfortunately this plugin falls afoul of. It would be great if it could be updated to adhere to this.

**Comment by PeterJCLaw** [comment]
Hrm, alternatively users may want to consider https://pypi.org/project/flake8-modern-annotations/

**Comment by atollk** [comment]
Should be fixed in v2.0. Let me know if there are still issues.
But yeah, for the latest versions of Python, that other package you linked might just be the better option in general :)
